import product1 from '../../assets/images/product1.png';
import product2 from '../../assets/images/product2.png';
import product3 from '../../assets/images/product3.png';
import product4 from '../../assets/images/product4.png';
import product5 from '../../assets/images/product5.png';

export const products = [
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		product_name: "My Product5",
		img: product5,
		price: 300,
		original_price: 300,
		discount: -33,
		ratings: 4,
		no_of_rates: 100,
	},
];

export const bestSellings = [
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];

export const explore = [
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
];

export const recommendations = [
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];

export const wishList = [
	{
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];
