import product1 from '../../assets/images/product1.png';
import product2 from '../../assets/images/product2.png';
import product3 from '../../assets/images/product3.png';
import product4 from '../../assets/images/product4.png';
import product5 from '../../assets/images/product5.png';

export const products = [
	{
		id: 1,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 2,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 3,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 4,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		id: 5,
		product_name: "My Product5",
		img: product5,
		price: 300,
		original_price: 300,
		discount: -33,
		ratings: 4,
		no_of_rates: 100,
	},
];

export const bestSellings = [
	{
		id: 6,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 7,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 8,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 9,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];

export const explore = [
	{
		id: 10,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 11,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 12,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 13,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		id: 14,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 15,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 16,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 17,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
];

export const recommendations = [
	{
		id: 18,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 19,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 20,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 21,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];

export const wishList = [
	{
		id: 22,
		product_name: "My Product1",
		img: product1,
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		id: 23,
		product_name: "My Product2",
		img: product2,
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		id: 24,
		product_name: "My Product3",
		img: product3,
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		id: 25,
		product_name: "My Product4",
		img: product4,
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	}
];
