export const products = [
	{
		product_name: "My Product1",
		imageSrc: "images/product1.png",
		price: 120,
		original_price: 160,
		discount: -40,
		ratings: 4,
		no_of_rates: 81,
	},
	{
		product_name: "My Product2",
		imageSrc: "images/product2.png",
		price: 140,
		original_price: 180,
		discount: -35,
		ratings: 2.5,
		no_of_rates: 73,
	},
	{
		product_name: "My Product3",
		imageSrc: "images/product3.png",
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		imageSrc: "images/product4.png",
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		product_name: "My Product5",
		imageSrc: "images/product5.png",
		price: 300,
		original_price: 300,
		discount: -33,
		ratings: 4,
		no_of_rates: 100,
	},
	{
		product_name: "My Product3",
		imageSrc: "images/product3.png",
		price: 139,
		original_price: 164,
		discount: -24,
		ratings: 3,
		no_of_rates: 22,
	},
	{
		product_name: "My Product4",
		imageSrc: "images/product4.png",
		price: 122,
		original_price: 156,
		discount: -35,
		ratings: 4,
		no_of_rates: 88,
	},
	{
		product_name: "My Product5",
		imageSrc: "images/product5.png",
		price: 300,
		original_price: 300,
		discount: -33,
		ratings: 4,
		no_of_rates: 100,
	},
];
